### ISSUE TITLE
Research workplace health and safety (incl. WSIB) requirements

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#123]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/70#issuecomment-538146143

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We understand our current obligations and have taken steps to comply.  

@uditvira brought this up as a question for Hema, but she recommended we contact WSIB ourselves.

See: **Compliances** section of our business plan, which discusses:
:lock: https://link.hypha.coop/business-plan#heading=h.su6qcs6mrogj

## To Do

- [x] research/identify relevant legislation
  - [Occupational Health and Safety (OSH) Act](https://www.ontario.ca/document/guide-occupational-health-and-safety-act)
  - [Workplace Safety and Insurance Act](https://www.wsib.ca/en/policy/workplace-safety-and-insurance-act)
    - [Reg 1101: First Aid Requirements](https://www.wsib.ca/sites/default/files/2019-09/0455_english_2014.pdf)
- [x] verify Workplace Safety and Insurance Board (WSIB) requirements
  - [x] research WSIB requirements. Per below, we are in a **by application** industry
  - [x] **stretch** complete WSIB online registration
  - [x] **stretch** provide followup information
    - if required: must be done within 10 days of hiring first employee [(ref)](https://learn.marsdd.com/article/setting-payroll-ontario/)
    - if not required: will receive **tender letter** that indicates it is optional (our path)
- [x] file our [WSIB letter](https://drive.google.com/file/d/1pukxxpYJsNqGGyS56FL5vttfH6wUlSCK/view?usp=sharing) :lock:  (confirmed we are **non-mandatory** industry.

**Comment by patcon** [comment]
Feel free to flesh this out udit!

**Comment by dcwalk** [comment]
We hinted at source to this in the business plan, there are resources online for Occupational Health and Safety (OSH) Act https://www.ontario.ca/document/guide-occupational-health-and-safety-act and WSIA: https://www.wsib.ca/en/policy/workplace-safety-and-insurance-act

And here is stuff on WSIB:
https://www.wsib.ca/en/employer-classification-manual/software-development-and-computer-services

https://www.blaney.com/articles/my-accountant-says-i-should-have-registered-with-wsib-ten-years-ago-now-what-do-i-do

**Comment by dcwalk** [comment]
And this is helpful for reporting req's: https://www.ccohs.ca/oshanswers/legisl/injury_reporting.html

**Comment by dcwalk** [comment]
Notes from call (1-800-387-0750) with [WSIB](https://www.wsib.ca/en/contact-us) on 2019-12-07:

- Computer and software development is  a non-standard coverage area. One the phone confirmed it is considered "by application", which means **not required**.
- may be in the situation where we are asked for a "[clearance certificate](https://onlineservices.wsib.on.ca/Clearances/eclearance/start)" from a client. This is a letter issued by WSIB indicating we are in good standing with paying our premiums
- However there is another option to indicate we've followed up and are in good standing without coverage, called a "tender letter." This makes clear we've spoken to WSIB and confirmed we are in a non-covered industry.
  - To obtain: On the website fill out [registration form online](https://eservices.wsib.on.ca/portal/server.pt/community/eservicespublic/eregistration)
  - Account Rep will review and issue a letter saying we do not require coverage (or saying we do)
  - From that letter, we can elect to obtain coverage after that date (by filling out an application will have an inactive account in the system)
- Premiums calculated on a per $100 of insurable earnings
  - For our industry the premium is pretty low, $0.19/$100 (Apparently this is one of the lowest).
- However, in 2020 moving into CRA NAICS-aligned rate structure. This means switching from ~130 "rate groups" into ~35 "classes", there will be a reasonable increase at that time

ping @patcon

**Comment by patcon** [comment]
Thanks @dcwalk!

I just realized I don't know: What sort of time horizon do you hope or expect we might opt-in for?

**Comment by dcwalk** [comment]
I don't have a set horizon in mind that should be discussed and agreed upon as a group. 

My take, clarifications:
- Commuting to a jobsite is not typically considered "in the course" of a job and I believe would not be a workplace injury / eligible for WSIB coverage per [Ross & McBride LLP in Hamilton](http://rossmcbride.com/) [(ref)](https://www.thespec.com/shopping-story/8143884-legal-matters-injured-while-driving-to-work/) and the resource you linked. As such I do not think that both coworking and client spaces could count as "travel on employer's business" (going to a client for a meeting appears to meet the criteria, but the coworking space if it is our regular jobsite would not be?)
- The status of telecommuting/remote jobsites is underdefined in the acts and apparently there are contradictory precedents, I assume that would impact any interpretation of "remote office"
- "**Workers are covered by WSIB even if their employer is behind on its payments or has not registered in the first place.**" per [Siskind LLP in London](https://www.siskinds.com/injured-while-driving-for-work-common-questions-about-wsib/)
- The reason we are an exempt industry is because the chance for workplace injuries is deemed very low. The more compelling reason to pursue WSIB is likely to limit liability and prevent ability for litigation from an employer standpoint
- Worker's comp makes up only a small piece of employer provisions incl. sick leave, disability, etc... in my experience in former workplaces those pieces are extremely important in any fulsome response to an injury that has happened at work

**Comment by dcwalk** [comment]
Chatted in 2020-01-29 call, we'll proceed with registering and obtaining a tender letter!

**Comment by dcwalk** [comment]
Filed the letter, moving implementation to #217
