### ISSUE TITLE
Create client agreement template

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/organizing#201]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Merge client agreement template into handbook.  

Draft client agreement template based on existing plain-language contract @patcon uses for an existing client, which members have already reviewed. Use this as a template to create agreements for future clients.

## To Do

- [x] Draft client agreement template
- [x] ~~Merge template into~~ Link template from handbook

**Comment by dcwalk** [comment]
I’m not sure that the best place for a template to live will be in the handbook. The current contract is a Google Doc and it makes sense to me that we’ll need a template with more formatting and layout options than markdown allows

**Comment by benhylau** [comment]
I have a secret hope that we can eventually generate internal proposals and contracts via a yaml, similar to how we make visa letters at ournetworks :)

I also don't see markdown being too restrictive as I have made contracts with signature boxes and letterheads, but let's start with a Google Doc and see how that goes. Here it is for review:

https://docs.google.com/document/d/1nmPX8k3TSEEUYx7cFaOoVNKbwjhp8nbUZwe6OdvC7Do/edit#

**Comment by uditvira** [comment]
I'm not the biggest fan of this agreement for a couple of reasons:

1. The language is extremely opinionated. Being opinionated in itself isn't a problem for me, but the opinions here don't feel like ours. If we were to go down the path of an opinionated contract, I'd rather start from scratch and develop something that feels like Hypha.
2. It's verbose. While the language is simple, it's lengthier than most contracts I've seen. Standard contracts might have more jargon, but they're also more succinct.

My preference would be for a more straight forward "Statement of Work" such as those shown [here](https://www.docsketch.com/contracts/). That being said, I won't block if there is a strong sentiment in favour of the current proposal.

**Comment by dcwalk** [comment]
I'm +1 on something that has a more informal vibe over a rote statement of work with the following thoughts:
- Agree that if we want something opinionated/colloquial like this we should adapt and write for ourselves. 
- Think we could have something plain language with way less words (I did a pass of the first section to showcase what that might look like). Maybe we start there and build up?
- Overall the sections make sense, I would favour a little more detail on the schedule side than the current format allows 
- Might be nice to have placeholder text as a guide, as frequently when drawing up contracts/job descriptions I refer to previous ones

**Comment by benhylau** [comment]
I posted this message a while back on the public room. I got only a response from @dcwalk. Since then I have mentioned in chat a couple times that "I am working on the client agreement template."

<img width="877" alt="Screen Shot 2020-02-25 at 8 50 44 PM" src="https://user-images.githubusercontent.com/2261308/75281991-91611080-5810-11ea-8cfa-ae24f614a5ea.png">

I feel that an organization, this work should not have begun until we all agreed that the general direction is right. For the PIAA, I have gone through an extensive consultation process on Loomio, but for this I only asked in chat, which I understand is not the agreed upon way of polling people's opinions. However, I didn't feel it'd get much more participation on GitHub/Loomio either. So I felt at least I have buy-in from @dcwalk and @patcon (who generally promotes this contract language and have signed the original with a client), and since no one else responded with a block, I proceeded to do the task.

In this specific case, I feel the process failed, but I don't know of a better way to move things along.

**Comment by patcon** [comment]
+1 on gdocs

auto-gen direction is neat and i support, but hope not to end up in more rigid doc platform like github in meantime

note that at Myplanet, contracts became stylish deliverables with graphics and things, which markdown seems less obviously favourable to. but i'm open to whatever

disclaimer: i like informal aesthetic.

but i respect his opinion and experience here. open to being convinced that informal might be poor choice, just not sure why that might be. happy to start with "cut-and-dry" option someone can choose if they prefer. esp because it's quick and less discussion.

One option: just buy a dry statement of work template like 99% of the rest of the world uses (v little need for input). Get a +1 on that as an option. Then we have a clear baseline that would never stall a prospect (as perhaps our informal one might, if it doesn't feel SERIOUS BUSINESS enough). Informal contract seems like it'd need more discussion and participation than is being offered now. I personally expect to be particularly energized to riff on this when there's a new and specific client in mind. Though that's not very proactive ;)

We could also host a short discussion in all hands, asking what folks experience and expectations are around contracts. What should they do? What should they communicate? What should we be different on, or cookiecutter? Any inspos? Should legals docs have an aesthetic or tone, and to what end? Even just in this issue, there's clearly some different opinions we could hash out or surface :)

Anyhow, thanks ben. Sorry your energy got zapped on this one

**Comment by patcon** [comment]
🤷‍♂ https://twitter.com/patconnolly/status/1237898181255421952

**Comment by benhylau** [comment]
Update copy based on feedback to use more neutral tone. Please review again:

https://docs.google.com/document/d/1nmPX8k3TSEEUYx7cFaOoVNKbwjhp8nbUZwe6OdvC7Do/edit#

**Comment by uditvira** [comment]
> Update copy based on feedback to use more neutral tone. Please review again:
> 
> https://docs.google.com/document/d/1nmPX8k3TSEEUYx7cFaOoVNKbwjhp8nbUZwe6OdvC7Do/edit#

I'm fine to move forward as is. Accepted changes, left one suggestion, and synced to our look and feel.

**Comment by dcwalk** [comment]
Looks good, I did a quick read and made some readability edits and ones spacing suggestiion. Good to merge to me :+1:

**Comment by dcwalk** [comment]
@benhylau I think this is ready for sign-off!

**Comment by benhylau** [comment]
Made https://link.hypha.coop/client-agreement and added PR to handbook. Close this after merge.

**Comment by conatus** [comment]
Alex from Common Knowledge, a coop out in the UK diving in. 

We have our own contract we like to use but this discussion has made it clear to me we could perhaps be more mindful about it. 

If you wanted to add hello@commonknowledge.coop to that Google Doc in the spirit of sharing, that would be awesome. Thanks!

**Comment by benhylau** [comment]
Hey @conatus thanks for popping by :)

I have added your hello@commonknowledge.coop to that document. We are writing many other documents over next couple weeks as we approach our AGM. I have created #273 to track making all of them fully public.
