### ISSUE TITLE
Bug: Shared calendar doesn't allow non-owner members with write permissions to send calendar invites

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/organizing#419]
I learned this while creating calendar events in the shared COMPOST calendar (@benhylau is owner, Mai and I have r/w permissions).

It doesn't work because SoGo tries to send the calendar invite as user giving the following error:
`SMTP(RCPT TO) error: 5.7.1 <elon@hypha.coop>: Sender address rejected: not owned by user`

This is a well known issue https://www.sogo.nu/bugs/view.php?id=2702

@hyphacoop/infrastructure-wg can we get some guidance on how to create/manage shared calendars?

**Comment by ASoTNetworks** [comment]
As discussed today in our all hands with different variations of how different email / calendar clients handles sending out invites.

A possible work around is to have a shared email account example: `calendar@hypha.coop` that manages all the shared calendars and shared to corresponding members with write access in SOGo and allow all members to send from `calendar@hypha.ooop` in Mailcow users' setting.

When a member adds a new event in their own SOGo account into the shared calendar the outgoing invitation email can be sent from `calendar@hypha.ooop` using their own account.

**Comment by ASoTNetworks** [comment]
I have created a shared calendar email account `calendar@hypha.coop` with the password in our Passbolt.

To create a shared calendar login to `calendar@hypha.coop`
1. Go to the calendar tab
1. Create a New Calendar
1. Click on three dots, click on `Sharing`
1. Add the users you want to share with and your own email account.
1. Check the `Subscribe User` checkbox so that the calendar automatically shows up in their Sogo
1. Select appropriate permissions
1. Check `This person can create objects in my calendar.` and `This person can erase objects from my calendar.`
1. Logout of the `calendar@hypha.coop` and into your own account on Sogo.
1. You should now see a new calendar shared from `calendar@hypha.coop` you can add events in there and invitations will be sent from `calendar@hypha.coop` to the recipient.

**Comment by garrying** [comment]
Aiming to close issue by March 27. Please post any feedback on the workaround!

**Comment by garrying** [comment]
@uditvira gonna close this for now. let's reopen or create a new issue if there are issues with the flow above.
